import type { Metadata } from "next";
import Link from "next/link";
import { requireAuth } from "@/features/auth/actions";
import { getPullRequests } from "@/features/pull-requests/server/get-pull-requests";
import { getInstallationStatus } from "@/features/github/server/installation";
import { DashboardHeader } from "@/features/dashboard/components/dashboard-header";
import { PullRequestsList } from "@/features/pull-requests/components/pull-requests-list";
import { Button } from "@/components/ui/button";
import { DASHBOARD_ROUTES } from "@/features/dashboard/lib/routes";

export const metadata: Metadata = {
  title: "Pull Requests · Dashboard",
};

function PRsNotConnected() {
  return (
    <div className="flex flex-1 flex-col items-center justify-center gap-4 p-6">
      <p className="text-sm text-muted-foreground">
        Install the GitHub App first to see your pull requests.
      </p>
      <Button nativeButton={false} render={<Link href={DASHBOARD_ROUTES.github} />}>
        Go to GitHub App
      </Button>
    </div>
  );
}

export default async function PullRequestsPage() {
  const session = await requireAuth();
  const installation = await getInstallationStatus(session.user.id);

  const header = (
    <DashboardHeader
      title="Pull Requests"
      description="History of all pull request code reviews generated by PR Panda."
    />
  );

  if (!installation.connected) {
    return (
      <>
        {header}
        <PRsNotConnected />
      </>
    );
  }

  const pullRequests = await getPullRequests(session.user.id);

  return (
    <>
      {header}
      <PullRequestsList pullRequests={pullRequests} />
    </>
  );
}
